#--- PaginaWeb
version: '3'
services:
  web:
    # Path to dockerfile.
    # '.' represents the current directory in which
    # docker-compose.yml is present.
    build: .

    # Mapping of container port to host
    
    ports:
      - "5000:5000"
    depends_on:
      - database
    # Mount volume 
    environment:
      - "MYSQL_ROOT_PASSWORD=${VAR1}"
      - "MYSQL_USER=${VAR2}"
      - "MYSQL_PASSWORD=${VAR3}"
      - "MYSQL_DATABASE=${VAR4}"
    # Link database container to app container 
    # for reachability.
    links:
      - database:database
    
  database:

    # image to fetch from docker hub
    image: mysql/mysql-server:5.7
    restart: always
    container_name: database
    hostname: database


    # Environment variables for startup script
    # container will use these variables
    # to start the container with these define variables. 
    environment:
      - "MYSQL_ROOT_PASSWORD=${VAR1}"
      - "MYSQL_USER=${VAR2}"
      - "MYSQL_PASSWORD=${VAR3}"
      - "MYSQL_DATABASE=${VAR4}"
    # Mount init.sql file to automatically run 
    # and create tables for us.
    # everything in docker-entrypoint-initdb.d folder
    # is executed as soon as container is up nd running.
    volumes:
      - "/usercode/db/init.sql:/docker-entrypoint-initdb.d/init.sql"
    